name: Jake Israel
favicon: null
layout_spectrum: 0.09139447775669396
typography_spectrum: 0.07639790535904467
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.817700122250244
  lightness: 0.6339056917931885
  saturation: 0.40730201569385827
  rhythmicContrast: 0.5430204772856086
purpose: []
